### ISSUE TITLE
How is Baretest different from Zora?

### ISSUE THREAD

**Issue by lorenzofox3** [volument/baretest#2]
greetings from [pta](https://github.com/lorenzofox3/zora-node) and [zora](https://github.com/lorenzofox3/zora) ;) 

I think we have some feelings in common !

Don't hesitate to add baretest to the "benchmark" in zora's repository

Cheers

**Comment by tipiirai** [comment]
Hey there! Nice to see Zora — looking really good. We seem to have a lot in common and we share the same engineering philosophies. 

However, I want to point out some subtle differences since here since one person asked about it and I'm pointing them all here.

1. *Features.* Zola has more features like the built-in assertion library, grouping, TAP protocol support/custom reporters, and browser support. It's an obvious choice when those features are needed. Bareserver is stripped down to the very basics. 

2. *Boringness.* Baretest is stamped with long term support (LTS) after it is proven stable. The mere ~60 lines of code are easy to stabilize and we want to leave it there for years to come. We want it to be a boring project that never changes.

3. *Install size* Zora is six times bigger (99.5Kb vs 16.1kB). I just wanted to mention this since this is one of Zora's [selling points](https://github.com/lorenzofox3/zora/#focus-on-tests-only). 

5. *Performance.* The most essential metric for Baretest is the _startup time_ because most of the time we just run a single test with the `only` call. Our benchmark would be wired differently, for example by measuring how long it takes to run `node ./my-test` 100 times. I suppose we need to make this and also include Baretest on Zola's bench.

Having said all that, I'm pretty certain Zola is absolutely on the same ballpark in terms of features and ease of use. I really enjoyed your README and would definitely choose your project over Mocha, Jest, AVA, and all. In both projects, the API documentation is super thin. Designed to fit into your brain so you never need to look for docs while developing. One small difference, however, is that Baretest embraces Node's assertion library, which is considered the standard.

Anyway, good stuff. I just heard about Zora yesterday.

Thanks!

**Comment by lorenzofox3** [comment]
> Install size Zora is six times bigger (99.5Kb vs 16.1kB). I just wanted to mention this since this is one of Zora's selling points.

This is correct. Mainly due to point 1 and 2. Zora is intended to be more flexible and a starting block for custom testing experience. For the record you can find a [small zora at the end of this article](https://dev.to/lorenzofox3/there-is-beauty-in-simplicity-1npe) (about the same size as baretest) with the same constraints/requirements than baretest. 

> 4. Performance. The most essential metric for Baretest is the startup time because most of the time we just run a single test with the only call. Our benchmark would be wired differently, for example by measuring how long it takes to run node ./my-test 100 times. I suppose we need to make this and also include Baretest on Zola's bench.

This is interesting. Zora on the other hand aims at be fast running **all** tests. I personally find [the only pattern](https://github.com/lorenzofox3/zora/issues/16#issuecomment-541246033) dangerous if not implemented correctly 

> One small difference, however, is that Baretest embraces Node's assertion library, which is considered the standard.

This is correct. At the time of writing zora, it was tricky to bring ``assert`` module to the browser and had to implement an assertion library (highly inspired by ``tape``), the little zora aforementioned does not have that constraint. I am not sure whether it would still be the case now.

I'll keep an a eye on baretest, it looks promising ! congrats

**Comment by newtack** [comment]
As a user Zora I am very, very happy with it. Performance is a feature and we have almost 1,000 tests that run in about 3 seconds. 

Also, even if baretest brings down the startup overhead, why restart node unnecessarily? We simply have an aggregate file that just aggregates other test files thereby we have only one startup (which with Zora is also very fast).

**Comment by tipiirai** [comment]
There are no problems with the `only` method in Baretest. Internally the functionality with both normal and `only` tests are exactly the same: run an array of JavaScript functions. We use the only- pattern much more often than running trough all the tests (like 100 per 1)  — this is why the startup time is so essential for us. 

Benchmarking startup time is a great way to measure the overhead of a test runner. Of course, running all the tests also an essential benchmark. We will [verify our performance claims)(4) 🤝

Baretest will not include a custom assertion library so with the 16kB install size it remains this "extremely minimalistic" option with the smallest overhead, near-instant performance, and a super small API.

**Comment by lorenzofox3** [comment]
> There are no problems with the only method in Baretest. Internally the functionality with both normal and only tests are exactly the same

When discussing *only* in zora, my concern was not about implementation. It is more about the fact that in order to run a subset of tests you need to modify your testing program calling some sort of ``test.only`` method, making the testing program invalid for the rest of your team (if you forget to change back the ``test.only`` for example). 
It is more a convenience while developing and should, in my opinion, be handled at test runner level with something like ``baretest --only "some test"`` otherwise you are mixing the "what to run" with the "how to run".

In zora we have addressed this issue by using an environment variable flag (or global for the browser) when running the testing program in "only mode": ``RUN_ONLY=true node my/program.js``. So that if a ``test.only`` call is found whereas the program is not in "only mode" an exception is thrown. This makes forgotten ``t.only`` break the CI for example
